spring.application.name=micro-plot


server.port=8083

spring.datasource.url=jdbc:mysql://127.0.0.1:3306/micro_plot
spring.datasource.username=root
spring.datasource.password=0417@2003
spring.jpa.hibernate.ddl-auto=update