spring.application.name=micro-apiGetaway

server.port=9000

#configretion EUREKA client-create..................

eureka.client.service-url.defaultZone=http://localhost:8080/eureka

eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

spring.cloud.gateway.routes[0].id=MICRO-EMPLOYEE
spring.cloud.gateway.routes[0].uri=lb://MICRO-EMPLOYEE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/employees/**

spring.cloud.gateway.routes[1].id=MICRO-ACCOUNT
spring.cloud.gateway.routes[1].uri=lb://MICRO-ACCOUNT
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/account/**

spring.cloud.gateway.routes[2].id=MICRO-PLOT
spring.cloud.gateway.routes[2].uri=lb://MICRO-PLOT
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/plots/**
